Created Remote Debugging Training
microsoft/Federal-App-Innovation-Community pull request #56
Opened 2022-07-12 20:56 UTC by Patrick-Davis-MSFT

## Describe your Changes
Added training documents to remote debug on App Services

## Issue ticket number and link if relevant

## Checklist before requesting a review
- [x] I have performed a self-review of my code and documentation
- [x] I have updated the README to denote my solution/training/whitepaper
- [x] I have identified which clouds this can run (Azure Cloud / Azure Government)

2022-07-14 15:13 UTC, haithamshahin333 requested changes
@Patrick-Davis-MSFT great addition!

A few thoughts:

1. Would be great to show how the Debug release property is set when the deployment occurs to the app service. 

2. Notes on remote debugging in the context of a private App Service (Private Endpoint enabled) or ASE deployment that is internal. What ports are required inbound?

3. Is this capability supported in Azure Gov?

2022-07-18 13:57 UTC, Patrick-Davis-MSFT commented
Added AKS Training

2022-07-18 18:56 UTC, christopherwoodland approved these changes
Maybe rename readme.md to README.md throughout

2022-07-19 14:30 UTC, haithamshahin333 approved these changes

2022-07-19 20:49 UTC, merged